# Generated by Django 3.2.18 on 2023-03-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_vis', '0002_auto_20230321_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefugeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_refugees', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='MapVisRefugeedata',
        ),
    ]
