# Generated by Django 3.2.18 on 2023-03-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_vis', '0003_auto_20230321_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefugeeData',
        ),
    ]
